# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.7'

services:
  api:
    container_name: api_wiz_devedor
    image: devedor-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '5000:5000'
      - '5001:5001'
    networks: 
      - api-devedor-network
        
networks:
  api-devedor-network:
    driver: bridge